on:
  workflow_dispatch:
  workflow_call:

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "SHORT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: build-${{ env.SHORT_HASH }}
          path: './'
